apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: homeassistant-config-pv
  resources:
    requests:
      storage: 5Gi
